title: C++ 学习笔记
description: 我的编程成长记录
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

sass:
  style: compressed

kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax
  syntax_highlighter_opts:
    default_lang: cpp
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1